---
- name: mysql is started and enabled
  systemd: 
    name: mysql
    state: started
    enabled: yes

- name: stop mysql
  systemd:
    name: mysql
    state: stopped
  notify:
    - Restart MySQL
